"""first

Revision ID: 2f7cb67c24ce
Revises: 495b0624ea05
Create Date: 2024-07-16 18:00:51.689533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f7cb67c24ce'
down_revision: Union[str, None] = '495b0624ea05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'days', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'days', type_='unique')
    # ### end Alembic commands ###
