"""first

Revision ID: 44c6df7410b0
Revises: fd46c8f40886
Create Date: 2024-07-11 21:59:28.934731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44c6df7410b0'
down_revision: Union[str, None] = 'fd46c8f40886'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'days', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'days', type_='unique')
    # ### end Alembic commands ###
