"""first

Revision ID: 835acff8fce7
Revises: f38d28de306e
Create Date: 2024-07-11 18:35:41.692180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '835acff8fce7'
down_revision: Union[str, None] = 'f38d28de306e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo_day', sa.Column('status', sa.Boolean(), default=False, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo_day', 'status')
    # ### end Alembic commands ###
