"""first

Revision ID: b0717c758595
Revises: 835acff8fce7
Create Date: 2024-07-11 20:57:32.433106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0717c758595'
down_revision: Union[str, None] = '835acff8fce7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo_day', sa.Column('id', sa.Integer(), nullable=False, primary_key=True))
    op.drop_column('todo_day', 'task')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo_day', sa.Column('task', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('todo_day', 'id')
    # ### end Alembic commands ###
