"""first

Revision ID: f30afb21ecbb
Revises: dee5b31773ff
Create Date: 2024-07-16 18:30:18.902576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f30afb21ecbb'
down_revision: Union[str, None] = 'dee5b31773ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'days', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'days', type_='unique')
    # ### end Alembic commands ###
